### ISSUE TITLE
Using STM32F407VET6 with Arduino

### ISSUE THREAD

**Issue by nathanaherne** [stevstrong/Arduino_STM32#11]
Hi Steve, I am sorry if this isn't the correct place to ask but I asked on the gitter channel and have yet to get a response.

I purchased the STM34F407VET6 board that is recommended on the stm32duino wiki. Since then I have done a large amount of reading on how to get it working with Arduino. I have been unsuccessful on getting it working via USB and Arduino so I tried to get it working with the STlink on a STM32Discovery (MB997B). I have also been unsuccessful. I know it is possible to use these boards but I have been unable to find out how to do so. Would you be able to point me in the direction of how to get this board working however may be currently supported please?

**Comment by stevstrong** [comment]
Well, the best place to post your questions related to F4 boards is: http://www.stm32duino.com/viewforum.php?f=39
If you use the F4 core from my repo, then please post here: http://www.stm32duino.com/viewtopic.php?f=39&t=1976.

Btw, I usually use this kind of STLink: https://www.aliexpress.com/item/ST-Link-V2-stlink-mini-STM8STM32-STLINK-simulator-download-programming-With-Cover/32277220832.html

I do not have experience with disco boards nor the STLink from that kind of boards.
