### ISSUE TITLE
Problem with ADC conversion F407VGT6 Blackboard

### ISSUE THREAD

**Issue by romanlife** [stevstrong/Arduino_STM32#13]
Hi Steve,we corresponded on the website stm32duino, I under the nickname STM32_Discoverer. So, I can't run the multichannel_nodma sketch, the led doesn't blink, the data doesn't come to the serial port. I tried to compile for the Discovery Board and for the Board Generic STM32f407V. There is no result. Сan you tell me please, BlackBoard F407VGT6 (DIYMore) refers to the Discovery F407 or generic F407 in the Arduino IDE?

**Comment by stevstrong** [comment]
I tested the sketch on the [generic black F4VET6 board](http://wiki.stm32duino.com/index.php?title=STM32F407), because I don't have an F4VGT board.
The board with VGT chip onboard differs a bit from the VET board, so you have to find out where the LED is connected.
First try to blink the LED. If this works, we can go for the next step.

**Comment by romanlife** [comment]
The LED onboard is PE0. After work today I will try to test the led

**Comment by romanlife** [comment]
So, I compiled the sketch MultiChannel_noDMA, as before, to the serial port nothing is displayed, the led is not flashing, it is lit constantly. Then I compiled a regular sketch in which I blink the led once a second and it works, the led blinks once a second. I think that the problem is in the command- Serial.begin

**Comment by stevstrong** [comment]
Do you have a schematic of the board?
Have you searched the original forum for the board and related problems?

**Comment by romanlife** [comment]
![STM32F407VGT6_diymore-2](https://user-images.githubusercontent.com/20615632/57159548-d41fab00-6dee-11e9-8562-6f454f67cd45.jpg)

**Comment by romanlife** [comment]
![STM32F407VGT6_diymore-3](https://user-images.githubusercontent.com/20615632/57159588-f0234c80-6dee-11e9-8f5c-7ac8f000232d.jpg)

**Comment by romanlife** [comment]
![DIY-More-STM32F407VGT6](https://user-images.githubusercontent.com/20615632/57159606-f9141e00-6dee-11e9-9190-e02fa298cabd.png)

**Comment by romanlife** [comment]
basically I'm looking for information on the site stm32duino, but I did not find such a problem there

**Comment by stevstrong** [comment]
Did you try to use serial1? This is the UART 1.

**Comment by stevstrong** [comment]
And i think you need to close a jumper to Boot0 and Gnd.

**Comment by stevstrong** [comment]
And i think you need a 1.5k resistor on USB Dp (D+) to 3.3v.

**Comment by romanlife** [comment]
Yes Steve, on a photo a jumper boot0 is not present, but at me on a Board I already soldered it. You were right as soon as I switched to Serial1.begin everything worked, the diode flashes, data is transmitted to the serial port!!!!!!!!the sketch works.

**Comment by romanlife** [comment]
I really appreciate your help, Steve

**Comment by romanlife** [comment]
the problem is solved,thanks Steve

**Comment by stevstrong** [comment]
Can you please tell me how did you solve the problem? It is usefull for anyone else having the same issue.

**Comment by romanlife** [comment]
The problem was  that the sketch - multichannel_nodma compiles, but  but when I download it into the Board the led doesn't blink, the data doesn't come to the serial port. I used in Setup - Serial.begin(115200);But then  you recommended to try to use serial1 instead serial declaration in Setup, so I change Serial.begin(115200); - to Serial1.begin(115200); and the LED onboard flashes, data is transmitted to the serial port!!!!!!!!the sketch - multichannel_nodma works.

**Comment by stevstrong** [comment]
So you did not try the 1.5k resistor on USB DP line to make USB work?

**Comment by romanlife** [comment]
no, I haven't installed a resistor yet, I download sketches via ST-LINK v2 programmer, and I don't use USB yet. I think soon I will try to solder the resistor and check the performance of usb
