### ISSUE TITLE
F3: Blinky sketch blinks faster if USB serial port is opened and connected to host

### ISSUE THREAD

**Issue by stevstrong** [stevstrong/Arduino_STM32#15]

**Comment by ag88** [comment]
no hurry with this one, i'm not sure why the rate changes as well

**Comment by stevstrong** [comment]
Because the current usb_serial has a timeout to send data. If not possible to send (not connected to the host), then the timeout period is added to the runtime.

**Comment by stevstrong** [comment]
Issue solved by https://github.com/stevstrong/Arduino_STM32/commit/a2a39455f8a50bce80234fc4b2a195f111c27b69.

**Comment by ag88** [comment]
thanks ! much improved !
