### ISSUE TITLE
adc_set_sampling_time for f3 

### ISSUE THREAD

**Issue by ag88** [stevstrong/Arduino_STM32#16]
- adc_set_sampling_time
in f3 setting the ADC sampling time calls adc_set_sample_rate()
https://github.com/stevstrong/Arduino_STM32/blob/master/STM32F3/cores/maple/libmaple/adc.c#L133
shall we rename that so that it is adc_set_sampling_time same as the f4?
actually f1 core is 'guilty' as well naming it incorrectly as adc_set_sample_rate()

**Comment by stevstrong** [comment]
Hi, would it be possible to separate these issues? It would be more efficient to track them. Thanks

**Comment by ag88** [comment]
sure thanks, i've leave the sampling time issue on this thread and created a new one for the fpu for f4.
note that on the f3 there is a minor extra indent in the fpu_enable() call that makes it looks a little less tidy, but this is simply cosmetic
https://github.com/stevstrong/Arduino_STM32/blob/master/STM32F3/cores/maple/boards_setup.cpp#L89

**Comment by stevstrong** [comment]
Fixed with #16.

**Comment by ag88** [comment]
thanks !
