### ISSUE TITLE
systick_attach_callback() isn't in the header for F3 core

### ISSUE THREAD

**Issue by ag88** [stevstrong/Arduino_STM32#18]
void systick_attach_callback(void (*callback)(void)) is in systick.c
https://github.com/stevstrong/Arduino_STM32/blob/master/STM32F3/cores/maple/libmaple/systick.c#L75

but it isn't declared in the header systick.h
https://github.com/stevstrong/Arduino_STM32/blob/master/STM32F3/cores/maple/libmaple/systick.h

this should be included in the header so that sketches can attach a systick handler if needed.

**Comment by ag-123** [comment]
did it first little PR
https://github.com/stevstrong/Arduino_STM32/pull/19
