### ISSUE TITLE
RTClock for f3

### ISSUE THREAD

**Issue by ag-123** [stevstrong/Arduino_STM32#22]
i've got an initial working version
RTC changes quite a few files including rcc.h, pw.h, bkp.h, rtc.h, rtc.c etc
it is actually your F4 port adapted to F303C
i got the example working
as i touched several of the core files it is unlikely your own edits would be the same as mine
do you want it in a PR or do you prefer to work it yourself ?

it is on my F3_RTClock branch, you could take a look at the commit
https://github.com/ag-123/Arduino_STM32/tree/F3_RTClock

**Comment by ag-123** [comment]
i've proceeded to release the PR, hope  it'd help
https://github.com/stevstrong/Arduino_STM32/pull/23

**Comment by stevstrong** [comment]
Thanks a lot, I did merge it.

**Comment by ag-123** [comment]
thanks! i'd monitor your issues & forum as well just in case there are issues related to it
