### ISSUE TITLE
Install Core in PlatformIO

### ISSUE THREAD

**Issue by steffentrumpf** [stevstrong/Arduino_STM32#24]
I don't know if it is the right place to ask this, but I have no other idea, since the stm32duino forum is down.

What is the best/easiest way to install your Core in PlatformIO?

I did some researching, but could not find anything.

Thanks!

**Comment by stevstrong** [comment]
Hi,
I don't support PlatformIO, only Arduino IDE.

However, you may search or post here: https://mcu.selfip.com/index.php
This a the place which is visited by most of the (old, not available) forum members.

If you get Roger's core to work under PIO, then you only have to overwrite those files with the files fro my repo.
