### ISSUE TITLE
SDIO

### ISSUE THREAD

**Issue by saloid** [stevstrong/Arduino_STM32#25]
Hello.
Do You have some examples to work with SDIO in STM32F1? I have get here by following [this stm32duinoforum.com](http://stm32duinoforum.com/forum/viewtopic_f_39_t_2215.html) thread. I tried to follow this instruction, but i getting error right after `sd.begin()`:
```
_initSDHC_278: DMA->ISR: 0x0, DMA->CCR: 0x0, DMA->CNDTR: 0, DMA->CPAR: 0x0, DMA->CMAR: 0x0, DMA->IFCR: 0x0, SDIO->CLKCR: 0x43B2, SDIO->DTIMER: 0x0, SDIO->DCTRL: 0x0, SDIO->DLEN: 0, SDIO->DCOUNT: 0, SDIO->STA: 0x0, SDIO->FIFOCNT: 0
SdFatSdio begin() failed
Can't access SD card. Do not reformat.
SD errorCode: 0X25,0X0
```
Sorry if it's wrong place for question.

**Comment by stevstrong** [comment]
You have tried to use the SDIO made for F4 in an F1-based project. This is not allowed.
SDIO has been ported from F4 to for F1 about 2 years ago, check this: http://stm32duinoforum.com/forum/viewtopic_f_58_t_2568.html
So please use the F1 version of SDIO from the official repository.
