### ISSUE TITLE
Broken links 

### ISSUE THREAD

**Issue by kd4pba** [stevstrong/Arduino_STM32#26]
Greetings,  
FYI
Not sure if you are aware many of the links provided are broken or no longer functional. 

http://www.stm32duino.com/

Does not appear to be a credible site. Appears to be a parked domain that refers to adverts or dead links. 

Section:
YouTube Videos:

    20141116: Arduino 1.5.8 IDE with STM32 board
    20150413: STM32 for Arduino 1.6.2 or newer (update)
    20150419: Uploading via USB to Serial to STM32F103 boards

None of these exist anymore.

**Comment by stevstrong** [comment]
Thanks for pointing out.
Resolved with https://github.com/stevstrong/Arduino_STM32/commit/9be8fffa596213f3b5b9f7d30b0e6a8bed71858c.
