### ISSUE TITLE
changes for flash.h, flash.c - ART accelerator

### ISSUE THREAD

**Issue by ag-123** [stevstrong/Arduino_STM32#30]
hi steve,
i'm planning a commit / pr for
STM32F4/cores/maple/libmaple/flash.h
and 
STM32F4/cores/maple/libmaple/flash.c

the main changes are the definitions for
FLASH_ACR register

my plan is to introduce the same ART accelerator defines as that used in the official core
https://www.stm32duino.com/viewtopic.php?f=7&p=527#p515

i found out, however, that the flash.h in STM32F4 core
https://github.com/stevstrong/Arduino_STM32/blob/master/STM32F4/cores/maple/libmaple/flash.h#L67
is using the definitions for stm32f103

there are 2 issues:
1   do you prefer that i update flash.h, flash.c directly or that i make a new file called flashF4.h and flashF4.c
2  this is giving me a dilemma, within F4* family there are variations
stm32F405, F407 has 3 bits in the latency field (i.e. up to 7 waits) while F401, F411 etc  has 4 bits in the latency field (15 waits)
how do we handle this? do we use definitions like ``STM32F405 , STM32F407, STM32F401, STM32F411``, and do if defs? do we add the underscores e.g. ``__STM32F405__``?
offcial core seem to use macro definitions without the underscores, but it is 'messy' whatever the case 
https://github.com/stm32duino/Arduino_Core_STM32/blob/master/cores/arduino/stm32/stm32_def.h#L33
https://github.com/stm32duino/Arduino_Core_STM32/blob/master/system/Drivers/CMSIS/Device/ST/STM32F4xx/Include/stm32f4xx.h#L75
https://github.com/stm32duino/Arduino_Core_STM32/blob/master/system/Drivers/CMSIS/Device/ST/STM32F4xx/Include/stm32f4xx.h#L144
another way though without the if defs, is to use just 3 bits for latency field. lowest common denominator. my guess is adequate for most cases except if one wants to overclock the processor. still anything more than 7 waits is quite extreme lol

**Comment by ag-123** [comment]
the changes are likely done 'incremental' than big bang, i.e. i may just update FLASH_ACR definitions, and start searching for references and updating them 

no plans for other registers just yet

**Comment by ag-123** [comment]
oops my goof, i found some definitions in rccF4.c
https://github.com/stevstrong/Arduino_STM32/blob/master/STM32F4/cores/maple/libmaple/rccF4.c#L138
i've been looking for them in flash.h

**Comment by stevstrong** [comment]
I think we can live with 3 bits, I am not a friend of ifdefs, only if necessary.

**Comment by ag-123** [comment]
i released a PR
https://github.com/stevstrong/Arduino_STM32/pull/32
there are no ifdefs ;)

the definitions are taken from the official core includes for stm32f4xx
i cross referenced f401, f411, (f405, f407, f415, f417 rm0009) and copied/adapted the definitions
pretty much all of them are there, i merged the definitions so long as they are non conflicting

**Comment by ag-123** [comment]
thanks much for merging the pr !
