### ISSUE TITLE
STM32F4: HardwareTimer.setperiod(uint32_t usecs) is making it running 2 times too fast.

### ISSUE THREAD

**Issue by ag88** [stevstrong/Arduino_STM32#36]
HardwareTimer.setperiod(uint32_t usecs) is making it running 2 times too fast.
https://www.stm32duino.com/viewtopic.php?p=736#p736

fix:
https://github.com/stevstrong/Arduino_STM32/blob/master/STM32F4/cores/maple/HardwareTimer.cpp#L57
```
uint16 HardwareTimer::setPeriod(uint32 microseconds)
...
  uint32 period_cyc = microseconds * (CYCLES_PER_MICROSECOND / 2);
```
change to 

```
uint16 HardwareTimer::setPeriod(uint32 microseconds)
...
  uint32 period_cyc = microseconds * (CYCLES_PER_MICROSECOND );
```

**Comment by stevstrong** [comment]
Thanks, fixed with commit https://github.com/stevstrong/Arduino_STM32/commit/7be4e70eb5bd770c6fd55144dd20df1956190387.
