### ISSUE TITLE
Unable to compile blink project when board Maple(RET6) is selected from Arduino studio

### ISSUE THREAD

**Issue by yuanb** [stevstrong/Arduino_STM32#42]
Hi, 

I hope this is the right place to log this issue, if not please close this issue and tell me where to log it

Environment:
OS: Mac OS X
Arduino Studio 1.18.12
STM32duino: 2020.6.20
Board: Leaflabs Maple RET6
Additional Board Manager URLs: http://dan.drown.org/stm32duino/package_STM32duino_index.json

Please check attached image for details. The same code compiles fine when Maple Rev3 is selected.
My remedy is to add the following to the beginning of Arduino15/packages/stm32duino/hardware/STM32F1/2020.6.20/cores/maple/sdio.cpp. Sample blink project, rtos blink project compiled and runs fine with this change.

Note, if I uncomment the #ifdef   __cplusplus block, the code wont compile, same error.

//#ifdef __cplusplus
//	#include <algorithm>
//	using namespace std;
//#else // C
	#include <stdlib.h>
	#ifndef min
		#define min(a,b) ((a)<(b)?(a):(b))
	#endif // min

	#ifndef max
		#define max(a,b) ((a)>(b)?(a):(b))
	#endif // max
//#endif // __cplusplus

![Screen Shot 2020-07-19 at 3 35 53 PM](https://user-images.githubusercontent.com/5303071/87883558-4077d180-c9d6-11ea-95d3-fd2b71e2fa61.png)

Board manager dialog:
![Screen Shot 2020-07-19 at 4 03 09 PM](https://user-images.githubusercontent.com/5303071/87884039-736f9480-c9d9-11ea-82e2-4ab859ada72e.png)

**Comment by stevstrong** [comment]
OK, I will have a look on this.

**Comment by stevstrong** [comment]
Your core files are from: http://dan.drown.org/stm32duino/package_STM32duino_index.json
This error is related to the Roger's core: https://github.com/rogerclarkmelbourne/Arduino_STM32
I think this is fixed by this commit: https://github.com/rogerclarkmelbourne/Arduino_STM32/commit/58ca12ab5bf7e844733897fbfb4cad790af1a50b
Please check out the new file sdio.cpp and try to compile again.

**Comment by yuanb** [comment]
@stevstrong  I don't understand how Arduino studio manage its packages. Are you saying I'm actually not using your code?

**Comment by stevstrong** [comment]
Yes, that is what I am saying.
If you want to use my core files, then you have to install it manually, identically as described here: https://github.com/rogerclarkmelbourne/Arduino_STM32/wiki/Installation
just that the package you have to download is this one: https://github.com/stevstrong/Arduino_STM32/archive/master.zip

**Comment by yuanb** [comment]
Thanks for letting me know, I forgot how my package was installed. I will try yours

**Comment by stevstrong** [comment]
It is good that it works with Roger's core, use that, you don't need to use my core.
Can you please  post the error messages as text?

**Comment by stevstrong** [comment]
I will close this as it seems to be resolved.
