### ISSUE TITLE
PR 753 rtc adjustments on original roger's core

### ISSUE THREAD

**Issue by ag88** [stevstrong/Arduino_STM32#43]
hi steve, can you help me commit this PR in roger's core?
[PR573](https://github.com/rogerclarkmelbourne/Arduino_STM32/pull/753)
this in part as someone asked about LSE compensation / drift adjustment
https://www.stm32duino.com/viewtopic.php?f=7&t=826
calibratertc(time_t time_now) lets user input the accurate time and computes the drift adjustments 
without this pr the function can only be called once. 
i think users tend to do a calibration and find that there is still a drift. 
A user used that and attempted to call the internal functions to fix the drift and i think an error/fault occured
writing to the backup registers.
https://github.com/rogerclarkmelbourne/Arduino_STM32/issues/731
[PR573](https://github.com/rogerclarkmelbourne/Arduino_STM32/pull/753)
resolves the problem as it allows the user to call calibratertc(time_t time_now) repeatedly and the drift adjustments  are refined with each additional call, it also avoided the potential error/fault as users won't need to 'fix' the drift by attempting to access the parameter in the backup registers directly

**Comment by stevstrong** [comment]
I just merged https://github.com/rogerclarkmelbourne/Arduino_STM32/pull/753.

**Comment by ag88** [comment]
thanks!
